spring:
  kafka:
    bootstrap-servers:
      - kafka1:29092
      - kafka2:29092
      - kafka3:29092

  datasource:
    url: jdbc:postgresql://postgres:5432/linktracker
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    enabled: true
    change-log: file:/app/migrations/master.xml

app:
  bot:
    base-url: http://bot:8080

  kafka:
    topic: link.raw-updates

  notification:
    transport: OUTBOX

  valkey:
    cache-type: CLIENT_SIDE
    standalone-node: valkey-standalone:6379
    password: ${VALKEY_PASSWORD:}

management:
  metrics:
    enable:
      http.server.requests.active: false
  prometheus:
    metrics:
      export:
        pushgateway:
          enabled: true
          address: pushgateway:9091
          job: scrapper
          push-rate: 15s
          shutdown-operation: post
          grouping-key:
            application: scrapper
            service_type: scrapper
