spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9094
      - localhost:9096

  datasource:
    url: jdbc:postgresql://localhost:5432/linktracker
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    enabled: true
    change-log: file:./migrations/master.xml

app:
  bot:
    base-url: http://localhost:8080

  valkey:
    cache-type: CLIENT_SIDE
    standalone-node: localhost:6385
    password: ${VALKEY_PASSWORD:}
